messages/package1_version_list.md, package.json, src/commands/force/package1/beta/version/display.ts, src/commands/force/package1/beta/version/list.ts, test/commands/force/package1/versionDisplay.nut.ts, test/commands/force/package1/versionList.nut.ts, yarn.lock
adds `package1:version:list` command
requires https://github.com/forcedotcom/packaging/pull/9
@W-10833181@
=> fix: add package1:version:list command, UTs, NUTs

messages/package_install.md, src/commands/force/package/beta/install.ts, test/commands/force/package/install.nut.ts, test/commands/force/package/install.test.ts, yarn.lock
Add spinner status to install
@W-0@
=> fix: improve human ux for install

messages/default.md, messages/package_delete.md, messages/package_version_create.md, messages/package_version_delete.md, messages/package_version_promote.md, src/commands/force/package/beta/version/delete.ts, test/commands/force/package/version.delete.test.ts, test/commands/force/placeholder.test.ts, yarn.lock
Add force:package:beta:version:delete command
@W-11444231@
=> fix: add pkg version delete command

README.md, command-snapshot.json, messages/package_version_report.md, package.json, src/commands/force/package/beta/version/create/report.ts, src/commands/force/package/beta/version/report.ts, test/commands/force/package/versionReport.test.ts, yarn.lock
Add package version report and package version create report commands
@W-11444248@
@W-11444281@
=> fix: add pvr pvcr commands

README.md, test/commands/force/package/versionReport.test.ts
update README and prevent some test command output
@W-0@
=> fix: update README and fix test output

package.json, yarn.lock
Bumps packaging lib version
@W-0@
=> fix: bump packaging library

src/commands/force/package/beta/version/create.ts
Corrects payload type for events for package version create
@W-11633216@
=> fix: type on event consumer for pvc

package.json, test/commands/force/package/install.test.ts, test/commands/force/package/installReport.test.ts, test/commands/force/package/version.delete.test.ts, yarn.lock
Adds chalk dependency directly rather than relying on a transitive dep.
@W-0@
=> fix: add direct chalk dependency

src/commands/force/package/beta/convert.ts, src/commands/force/package/beta/uninstall/report.ts, src/commands/force/package/beta/update.ts, src/commands/force/package/beta/version/create/list.ts, src/commands/force/package/beta/version/displayancestry.ts, src/commands/force/package/beta/version/list.ts, src/commands/force/package/beta/version/update.ts
Throw an error for all un-implemented beta commands.
@W-0@
=> fix: make command output clearer for un-implemented commands

messages/package_version_create.md, package.json, src/commands/force/package/beta/version/create.ts, yarn.lock
fix: add spinner and fix preserve file location msg
@W-11644909@
=> fix: add spinner and fix preserve file location msg

messages/package_version_update.md, package.json, src/commands/force/package/beta/version/update.ts, test/commands/force/package/versionPromoteUpdate.nut.ts, yarn.lock
adds `package:version:update` command
adds NUTs for pvu
enables NUTs for pvp
@W-10833226@
requires: https://github.com/forcedotcom/packaging/pull/25
=> fix: add package:beta:version:update and NUT

src/commands/force/package/beta/install.ts, src/commands/force/package/beta/install/report.ts
Shares common code between `package:install` and `package:install:report` using a static method on the install command.
@W-11757564@
=> refactor: share common pkg install code

messages/package_install.md, package.json, src/commands/force/package/beta/convert.ts, src/commands/force/package/beta/create.ts, src/commands/force/package/beta/delete.ts, src/commands/force/package/beta/install.ts, src/commands/force/package/beta/version/create.ts, src/commands/force/package/beta/version/create/report.ts, src/commands/force/package/beta/version/promote.ts, test/commands/force/package/install.test.ts, test/commands/force/package/versionPromoteUpdate.nut.ts, yarn.lock
fix: bump pkg lib to 0.0.42
@W-11784677@
=> fix: bump pkg lib to 0.0.42

package.json, test/commands/force/package/install.nut.ts, test/commands/force/package/packageCreateAndDelete.nut.ts, test/commands/force/package/packageInstalledList.nut.ts, test/commands/force/package/packageList.nut.ts, test/commands/force/package/packageVersion.nut.ts, test/commands/force/package/versionPromoteUpdate.nut.ts, test/commands/force/package1/versionCreate.nut.ts, test/commands/force/package1/versionDisplay.nut.ts, test/commands/force/package1/versionList.nut.ts, yarn.lock
Use latest cli-plugins-testkit
@W-11823417@
=> chore: use latest testkit

package.json, yarn.lock
=> fix: bump packaging

CONTRIBUTING.md, DEVELOPING.md, README.md
Remove sections of the README in favor of specific CONTRIBUTING and DEVELOPING docs, which were added.
@W-11949409@
=> fix: add doc for contributing to and developing in the packaging plugin

messages/package_uninstall_report.md, package.json, src/commands/force/package/beta/uninstall.ts, src/commands/force/package/beta/version/list.ts, test/commands/force/package/versionReport.test.ts, tsconfig.json, yarn.lock
Fixes order of parameters for frequency and wait for api uninstall
@W-12097786@
=> fix: pass wait correctly to api

bin/run, command-snapshot.json, package.json, yarn.lock
[@W-12085135@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12085135)
=> Parking orbit cleanup

.gitignore, command-snapshot.json, messages/package_version_create.md, messages/package_version_list.md, package.json, src/commands/force/package/beta/version/create.ts, src/commands/force/package/beta/version/list.ts
@W-11824088@ This PR adds support for adding language to package versions. Affected commands: package:beta:version:list and package:beta:version:create
=> feat: smusselman/add language 42

package.json, src/commands/force/package/beta/list.ts, test/commands/force/package/packageList.nut.ts, yarn.lock
remove deprecated package from the list produced by package:beta:list
@W-12228721@
=> fix: do not show deprecated packages

messages/package_version_create.md, package.json, yarn.lock
bump packaging lib version and update the flag description for `language`
@W-12377800@
=> fix: bump pkg library version and modify language flag description

package.json, src/commands/package/create.ts, src/commands/package/install.ts, src/commands/package/installed/list.ts, src/commands/package/version/create/list.ts, src/commands/package/version/list.ts, yarn.lock
Uses sf-plugins-core v2 and oclif/core v2
@W-10791948@
=> feat: use latest sf-plugins-core and oclif/core

package.json, yarn.lock
bump @salesforce/packaging from 1.4.2 to 1.4.3
@W-12513253@
=> fix(deps): bump @salesforce/packaging from 1.4.2 to 1.4.3

.mocharc.json, schemas/package-version-report.json, src/commands/package/version/report.ts, test/commands/package/versionReport.test.ts
@W-12965378@
Fix regression in package version report code coverage result in json
=> fix: restore json result to original for code coverga

test/commands/package/packageVersion.nut.ts, test/commands/package1/versionCreate.nut.ts
don't specify CLI
more asserts about before/setup for 1gp
full error output for 2gp
=> test: improve error output for NUTs

test/commands/package1/versionCreate.nut.ts
sometimes 1gp package create finishes before the test expects (it expects it to be queued first) which causes NUT failures.  This makes the tests more resilient to creation speed.
@W-00000000@
=> fix: make 1gp package version create tests more resilient

src/commands/package/version/retrieve.ts
Unhides the package:version:retrieve command now that 246 is going live. 
@W-13562915@
=> feat: unhide package:version:retrieve command (W-13562915)

package.json, yarn.lock
bump the version of the packaging library to get recent changes
@W-13932401@
=> fix: bump packaging lib

package.json, yarn.lock
bump library for new SDR types
=> fix(deps): core deps including SDR

package.json, yarn.lock
does anything bad happen if oclif/plugin-version is removed?
=> chore: remove oclif plugin version

command-snapshot.json, messages/package_convert.md, src/commands/package/convert.ts
Adds verbose capability to package convert.
@W-13992563@
=> feat: Adds verbose option to package convert

package.json, yarn.lock
https://github.com/forcedotcom/cli/issues/2609
[@W-14669279@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001gUdvHYAS/view)
=> fix(deps): bump packagin lib

README.md, command-snapshot.json, package.json, src/commands/package/version/create.ts, test/commands/package/packageCreateAndDelete.nut.ts, yarn.lock
Add `--flags-dir` to all commands by bumping @salesforce/sf-plugins-core to v8
=> feat: bump sf-plugins-core

package.json, test/tsconfig.json, tsconfig.json, yarn.lock
dependency bumps
remove plugin-auth as a oclif dev plugin
=> feat: library bump for sdr/customReg

package.json, schemas/package-convert.json, schemas/package-version-create-list.json, schemas/package-version-create-report.json, schemas/package-version-create.json, test/commands/package/install.test.ts, test/commands/package/installReport.test.ts, test/commands/package/packageConvert.test.ts, test/commands/package/packageUninstall.test.ts, test/commands/package/packageVersion.nut.ts, test/commands/package/packageVersionCreate.test.ts, test/commands/package/packageVersionCreateReport.test.ts, test/commands/package/packageVersionRetrieve.test.ts, test/commands/package/version.delete.test.ts, test/commands/package/versionPromoteUpdate.nut.ts, test/commands/package/versionReport.test.ts, test/commands/package1/versionCreate.test.ts, test/commands/package1/versionCreateGet.test.ts, yarn.lock
=> feat: core7, jsforce-node, etc

package.json, yarn.lock
bumps versions of pkg lib, core and plugins core to get a few fixes and library updates.
@W-15726916@
=> fix: bumps versions of pkg lib, core and plugins core

package.json, test/commands/package/packageVersion.nut.ts, yarn.lock
bumps deps
fixes NUTs with better types now
=> fix: bump deps, fix NUT types

src/commands/package/installed/list.ts, src/commands/package/version/create/report.ts, src/commands/package/version/report.ts
https://github.com/forcedotcom/eslint-config-salesforce-typescript/actions/runs/9717897647/job/27683284992?pr=246
=> fix(style): nullish template literals

schemas/package-pushupgrade-report.json, src/commands/package/pushupgrade/report.ts, test/commands/package/packagePushUpgradeReport.test.ts
=> feat: adds support for package version

src/commands/package/pushupgrade/schedule.ts
=> fix: split orgids according to new line for schedule command

command-snapshot.json, messages/package_pushupgrade_abort.md, schemas/package-pushupgrade-abort.json, src/commands/package/pushupgrade/abort.ts, test/commands/package/packagePushUpgradeAbort.test.ts
=> feat: adds pushupgrade abort command support

messages/package_version_create.md, package.json, schemas/package-convert.json, schemas/package-version-create-list.json, schemas/package-version-create-report.json, schemas/package-version-create.json, schemas/package-version-report.json, src/commands/package/version/create.ts, src/commands/package/version/report.ts, test/commands/package/packageConvert.test.ts, test/commands/package/packageVersion.nut.ts, test/commands/package/packageVersionCreate.test.ts, test/tsconfig.json, yarn.lock
Generate schema to include field TotalSizeOfMetadataFiles.
Add warning message if TotalSizeOfMetadataFiles > fileSizeThreshold
@W-17653027
=> W-17653027 add warning message if TotalSizeOfMetadataFiles exceeds 420MB

src/commands/package/version/report.ts
round up TotalSizeOfMetadataFiles to the next whole number
@W-17653027
=> W-17653027   round up TotalSizeOfMetadataFiles to the next whole number

LICENSE.txt, command-snapshot.json, messages/package_convert.md, package.json, src/commands/package/convert.ts, yarn.lock
adding a new parameter --patch-version  to package convert command for specific patch conversion
w 17625437
=> feat: adding new patch version conversion parameter

src/commands/package/push-upgrade/schedule.ts
=> @W-18650174 Fix start time required error

command-snapshot.json, messages/package_pushupgrade_abort.md, messages/package_pushupgrade_list.md, messages/package_pushupgrade_report.md, messages/package_pushupgrade_schedule.md, src/commands/package/push-upgrade/abort.ts, src/commands/package/push-upgrade/list.ts, src/commands/package/push-upgrade/report.ts, src/commands/package/push-upgrade/schedule.ts
=> @W-18683180 Fix help texts messages and remove beta flags

command-snapshot.json, messages/bundle_version_create.md, messages/bundle_version_list.md, schemas/package-bundle-version-list.json, src/commands/package/bundle/version/create.ts, src/commands/package/bundle/version/list.ts, test/commands/bundle/bundleVersionList.test.ts
It adds the package bundle version list command
=> feat: added package version list

src/commands/package/bundle/create.ts, src/commands/package/bundle/delete.ts, src/commands/package/bundle/install.ts, src/commands/package/bundle/install/list.ts, src/commands/package/bundle/install/report.ts, src/commands/package/bundle/list.ts, src/commands/package/bundle/version/create.ts, src/commands/package/bundle/version/create/list.ts, src/commands/package/bundle/version/create/report.ts, src/commands/package/bundle/version/list.ts, src/commands/package/bundle/version/report.ts
=> fix: hide bundles and state beta

command-snapshot.json, messages/bundle_install.md, messages/bundle_version_create.md, src/commands/package/bundle/install.ts, src/commands/package/bundle/install/list.ts, src/commands/package/bundle/install/report.ts, src/commands/package/bundle/version/create.ts, src/commands/package/bundle/version/report.ts, test/commands/bundle/bundleInstallReport.test.ts, test/commands/bundle/packageBundleVersionCreate.test.ts
=> T/packaging distribution/w 19170618/bug fixes

messages/package_version_retrieve.md
Edits the help text for package version retrieve.
@W-19842308@
=> W-19842308: Update package_version_retrieve.md
