salesforcecli/plugin-packaging

- src/commands/force/package/beta/install.ts
- test/commands/force/package/install.test.ts
Passes the installation key to `Package.getExternalSites()` and adds a unit test to ensure it's passed.
@W-0@
> fix: pass installation key when getting external sites

- messages/package2_create.md
- messages/package2_update.md
- messages/package2_version_create_get.md
- messages/package2_version_get.md
- messages/package2_version_update.md
Moves non-example content from # examples section to #help or #description
@W-11597858@
> fix: keep only examples in #examples section

- .github/workflows/test.yml
inject special nut env secret into workflow env (since nut job isn't otherwise aware of it)
> ci: env at workflow level

- package.json
- yarn.lock
version 0.1.17 of the packaging lib bumps the xmldom version to a non-vulnerable version.
@W-11111111@
> fix: bump packaging lib version to 0.1.17

- messages/package_version_create.md
- src/commands/force/package/beta/version/create.ts
- test/commands/force/package/packageVersionCreate.test.ts
fixes the way errors are displayed in the terminal.
1. create a package
2. now change the path in `sfdx-project.json` to point only to classes (as an example)
3. try to create a new package version
BEFORE:
```
Package version creation failed with unknown error. My_Object__c.My_Text_Field__c: Entity 'My_Object__c' not found.
Admin: In field: field - no CustomObject named My_Object__c found
```
AFTER:
```
ERROR running force:package:version:create: Multiple errors occurred:
(1) Admin: In field: field - no CustomObject named My_Object__c found
(2) My_Object__c.My_Text_Field__c: Entity 'My_Object__c' not found.
```
@W-11911836@
> fix: enumerate and format server errors better

- messages/package_version_create_report.md
- package.json
- src/commands/force/package/beta/version/create/report.ts
- test/commands/force/package/packageVersion.nut.ts
- test/commands/force/package/packageVersionCreate.test.ts
- test/commands/force/package/packageVersionCreateReport.test.ts
- yarn.lock
`force:package:beta:version:create:report` now will include errors
```
➜  sfdx force:package:beta:version:create:report -i 08c3i000000fyoVAAQ 
=== Package Version Create Request
Name                          Value              
───────────────────────────── ────────────────── 
ID                            08c3i000000fyoVAAQ 
=== Errors
(1) Create_property: geocode_address (Action) - We can't find an action with the name and action type that you specified.
(2) dreamhouse: In field: apexClass - no ApexClass named PagedResult found
(3) PropertyController: Variable does not exist: result
(4) PropertyController: Variable does not exist: result
```
changes the `--json` output to match toolbelt, toolbelt has an array of results, we were just returning the result
```diff
➜  sfdx …
```
> fix: print errors when reporting on a new PV with errors

- messages/package_install.md
- src/commands/force/package/beta/install.ts
- test/commands/force/package/install.test.ts
- test/commands/force/package/packageVersion.nut.ts
- tsconfig.json
When a package install polling timeout occurs, the request ID and query command message is now displayed as it was in the salesforce-alm plugin version of the command.  Also, the command returns an exit code of 0 and the `PackageInstallRequest` json (also matching the salesforce-alm plugin version of the command).
@W-12228879@
> fix: pkg install polling timeout should display how to query the status

- command-snapshot.json
- messages/package_convert.md
- package.json
- src/commands/package/convert.ts
What does this PR do?
Adds an optional command line parameter to the convert command so unpackageable metadata can be pushed to the build org that the packaged metadata depends on, such as StandardValueSets.
What issues does this PR fix or reference?
@W-12204966@
> feat: adds the seedMetadata command line parameter to the convert command

- package.json
- src/commands/package/install.ts
- test/commands/package/install.test.ts
- yarn.lock
when `--publish-wait` and `--wait` are provided, it will ensure the SPV is replicated, before checking for external sites or other prompts that require verification
requires: https://github.com/forcedotcom/packaging/pull/205
@W-12432030@
fixes:https://github.com/forcedotcom/cli/issues/1895
> fix: verify the SPV is availble to query, before checking deps

- src/commands/package/version/list.ts
The code was splitting on a space char when it needed to be a comma.
@W-12490382@
https://github.com/forcedotcom/cli/issues/1912
> fix: split on comma

- .github/workflows/test.yml
- package.json
- test/commands/package/packageVersion.nut.ts
Create yarn scripts to run package and package1 NUTs independently and change the GHA workflow to use them.
@W-12567087@
> chore: split package and package1 nuts

- test/commands/package/packageVersion.nut.ts
Enhance the `package:version:delete` NUTs to list the package versions after a delete and verify the deleted version is not in the list.
@W-00000000@
> fix: ensure deleted version is not listed

- test/commands/package/install.nut.ts
- test/commands/package/packageVersion.nut.ts
- test/commands/package/versionPromoteUpdate.nut.ts
- test/commands/package1/versionCreate.nut.ts
comands were updated to pass config.bin to the messages
NUTs needed to be updated to not hardcode expectations of `sfdx` in those messages.  
solve https://github.com/salesforcecli/cli/actions/runs/4867876480/jobs/8681253402
> test: packaging nuts assertions allow sf OR sfdx

- package.json
- yarn.lock
Bump `packaging` dependency to 2.1.2 to include recent fixes for `package version retrieve` command.
@W-12557202@
> chore: bump packaging dependency

- src/commands/package/version/create.ts
makes that flag require an existing file
> fix: make sure file exists with oclif

- src/commands/package/install.ts
plugin library passes around the `PackageInstallOptions`.  If you pass any options, it eventually gets to here
https://github.com/forcedotcom/packaging/blob/b7c470d07cfb0915752c37a84fbde04c534fc12d/src/package/packageInstall.ts#L199
where an undefined `frequency` will become `0`.
https://github.com/forcedotcom/cli/issues/2319
[@W-13797305@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001WeCjbYAF/view)
> fix: reduce polling frequency

- src/commands/package/update.ts
As 246 roles out we are now prepared to make visible the --enable-app-analytics flag on the sf package update command
@W-13153221@
> feat: make visible the enable-app-analytics flag to the sf package update command

- src/commands/package/version/retrieve.ts
@W-14169543 - Re-hide the `sf package version retrieve` command. This command will only work if the org has a newly introduced org perm. We will update the relevant error message in the `packaging` repo as well. 
@W-14169543@
> feat: hide 'package version retrieve' command

- package.json
- yarn.lock
bumps `packaging` lib to get rid of oclif/core v2 in prod
`npm why @oclif/core`
a few v2 coming from devDeps, only v3 in prod:
<details>
➜  plugin-packaging git:(cd/bump-packaging) npm why @oclif/core
@oclif/core@3.13.1
node_modules/@oclif/core
@oclif/core@"^3.11.0" from the root project
@oclif/core@"^3.0.4" from oclif@4.0.4
node_modules/oclif
dev oclif@"^4" from the root project
@oclif/core@"^3.5.0" from @oclif/plugin-command-snapshot@4.0.16
node_modules/@oclif/plugin-command-snapshot
dev @oclif/plugin-command-snapshot@"^4.0.16" from the root project
@oclif/core@"^3.12.0" from @oclif/plugin-warn-if-update-available@3.0.4
node_modules/@oclif/plugin-warn-if-update-available
@oclif/plugin-warn-if-update-available@"^3.0.0" from oclif@4.0.4
node_modules/oclif
dev oclif@"^4" from the root …
> fix: bump packaging lib

- package.json
- test/commands/package1/versionDisplay.nut.ts
- test/commands/package1/versionList.nut.ts
- yarn.lock
exit codes
https://github.com/salesforcecli/cli/actions/runs/7217237476/job/19665007192
> test: oclif exit codes

- package.json
- src/commands/package/create.ts
- src/commands/package/delete.ts
- src/commands/package/install.ts
- src/commands/package/list.ts
- src/commands/package/update.ts
- src/commands/package/version/create.ts
- src/commands/package/version/delete.ts
- src/commands/package/version/displayancestry.ts
- src/commands/package/version/promote.ts
- src/commands/package/version/report.ts
- src/commands/package/version/retrieve.ts
- src/commands/package/version/update.ts
- test/commands/package/install.test.ts
- yarn.lock
> requires https://github.com/salesforcecli/sf-plugins-core/pull/479
use the next version of sf-plugins-core for prompts 
had do do a lot of `this.project!` now that sfCommand properly types it as optional
@W-13801582@
> feat: use new inquirer via sf-plugins-core

- package.json
- src/commands/package/version/create.ts
- test/commands/package/packageVersionCreate.test.ts
- yarn.lock
Sets SF_APPLY_REPLACEMENTS_ON_CONVERT=true before converting packaged metadata so that strings are replaced automatically without the need for setting this env var explicitly. String replacement happens automatically during a deploy, so this matches the expected behavior.
@W-14914086@
> fix: set string replace env var before convert

- messages/package_version_list.md
- package.json
- schemas/package-version-list.json
- schemas/package-version-report.json
- src/commands/package/version/list.ts
- src/commands/package/version/report.ts
- test/commands/package/packageVersion.nut.ts
- test/commands/package/versionReport.test.ts
- yarn.lock
followup from - https://github.com/salesforcecli/plugin-packaging/pull/687
> feat: display validated-async in version list and report

- schemas/package-version-list.json
- src/commands/package/version/list.ts
- test/commands/package/packageVersion.nut.ts
Ref - [WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001nezqBYAQ)
@W-15398724@
Removing the `codeCoverage` field from the non-verbose query response for `package version list --json`
`codeCoverage` was an empty value for non-verbose response, which is incorrect.
> @W-15398724@ Remove codeCoverage field from non-verbose query response for package version list

- messages/package_install.md
- messages/package_version_create.md
- messages/package_version_delete.md
- src/commands/package/version/create.ts
@W-16217108@ - [WI](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001wQOe3YAG/view)
In this PR the Help text that displays with packageVersionCreatePerformingValidations and edited the definition-file flag was updated. These changes were requested by Dileep and handled by @penelopy
> @W-16217108@ fix: cli help text change for async validation

- src/commands/package/installed/list.ts
- src/commands/package/list.ts
- src/commands/package1/version/create.ts
- test/commands/package/packageInstalledList.nut.ts
- test/commands/package/packageList.nut.ts
- test/commands/package1/versionCreate.nut.ts
Allow the following commands to be run outside an sfdx project:
* `package installed list`
* `package list`
* `package1 version create`
the following ones still require an sfdx project:
* package delete
* package update
* package version displayancestry
* package version report
* package version delete
* package version promote
mostly because the packaging lib expects an `SfProject` instance to be able to resolve `--package` being an alias defined in sfdx-project.json.
internal doc: https://salesforce.quip.com/gnuNAtZkcOCP
we haven't decided on this work yet ⬆️ 
https://github.com/forcedotcom/cli/discussions/2932
@W-16189175@
> fix: allow some cmds to run outside a project

- .github/workflows/test.yml
- package.json
- src/commands/package/delete.ts
- src/commands/package/update.ts
- src/commands/package/version/delete.ts
- src/commands/package/version/displayancestry.ts
- src/commands/package/version/list.ts
- src/commands/package/version/promote.ts
- src/commands/package/version/report.ts
- src/utils/getProject.ts
- test/commands/package/packageCreateAndDelete.nut.ts
- test/commands/package/packageVersionCreate.test.ts
- test/commands/package/version.delete.test.ts
- yarn.lock
**DEPENDS ON https://github.com/forcedotcom/packaging/pull/638/files**
https://github.com/forcedotcom/cli/discussions/2932
Allow the following commands to be run outside an sfdx project:
* `package delete`
* `package update`
* `package version delete`
* `package version displayancestry`
* `package version list`
* `package version promote`
* `package version report`
@W-16286213@
> feat: make project optional

- messages/package_delete.md
- messages/package_version_delete.md
- test/commands/package/packageCreateAndDelete.nut.ts
- test/commands/package/packageVersion.nut.ts
- test/commands/package/version.delete.test.ts
We will be changing how `util.format` works when formatting messages. 
Specifiers (eg `%s`) will be required for the data to be rendered. As is, it appends data if no matching specifier is found.
More info here: https://github.com/forcedotcom/sfdx-core/pull/1099
[@W-16197665@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-16197665)
> Add specifier for message

- command-snapshot.json
- messages/package_pushupgrade_report.md
- package.json
- schemas/package-pushupgrade-report.json
- src/commands/package/pushupgrade/report.ts
- test/commands/package/packagePushUpgradeReport.test.ts
> feat: adds pushupgrade report command

- .gitignore
- command-snapshot.json
- messages/package_pushupgrade_list.md
- schemas/package-pushupgrade-list.json
- src/commands/package/pushupgrade/list.ts
- test/commands/package/packagePushUpgradeList.test.ts
> feat: Package Push Upgrade List command

- messages/package_version_promote.md
- test/commands/package/versionPromoteUpdate.nut.ts
Removes an old message about code coverage requirements for promoting unlocked package versions. The information is several years old.
It was a simple enough change that I didn't bother opening an issue.
> feat: remove outdated version create message

- src/commands/package/convert.ts
In preparation for 2GP GA, this PR exposes the "sf package convert" command via the CLI. It also exposes the --patch-version option.
Timelines for release:
June 4th - available as RC (Release Candidate)
June 11th - CLI Commands GA
June 14th (R2b) Core Code GA
@W-18491179@ Expose Conversions / Migrations CLI commands at GA
> W-18491179: expose package convert command for ga

- src/commands/package/version/create/list.ts
- test/commands/package/versionPromoteUpdate.nut.ts
Filters display record to exclude fields TotalNumberOfMetadataFiles and TotalSizeOfMetadataFiles for package:version:create:list command.
@W-19132026
> fix: filter displayRecord

- command-snapshot.json
- messages/package_version_displaydependencies.md
- package.json
- schemas/package-version-displaydependencies.json
- src/commands/package/version/displaydependencies.ts
- test/commands/package/packageVersion.nut.ts
[@W-17561980@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000027hh2GYAQ/view)
- Include `sf package version displaydependencies` command
- Include `--verbose` and `--edge-direction` flags
https://github.com/salesforcecli/plugin-packaging/pull/1011
> W-17561980 Complete CLI Command to Display Dependencies
